'use client';
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import { useEffect, useState } from 'react';
import type { Contribution } from '@/lib/contributions/model';
type Item = Omit<Contribution, 'sessionId'> & {media: { id: string; original_filename: string; mime: string; uploaded_at: string }[]};
function PrivateMedia({ id, mime, token }: { id: string; mime: string; token: string }) {
  const [url, setUrl] = useState('');
  useEffect(() => { let alive = true; let objectUrl = ''; fetch(`/api/contributions/media/${id}`, { headers: { Authorization: `Bearer ${token}` }, cache: 'no-store' }).then(r => { if (!r.ok) throw new Error(); return r.blob(); }).then(blob => { objectUrl = URL.createObjectURL(blob); if (alive) setUrl(objectUrl); else URL.revokeObjectURL(objectUrl); }).catch(() => undefined); return () => { alive = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [id, token]);
  if (!url) return <p>Attachment preview unavailable or loading.</p>;
  return mime.startsWith('image/') ? <img src={url} alt="Private citizen submission for moderation"/> : <a href={url} download="submitted-document.pdf">Download submitted PDF for inspection</a>;
}
export function ModerationQueue() {
  const [ready, setReady] = useState(false);
  useEffect(() => { setReady(true); }, []);
  const [token, setToken] = useState(''); const [activeToken, setActiveToken] = useState(''); const [items, setItems] = useState<Item[]>([]); const [error, setError] = useState(''); const [checked, setChecked] = useState<Record<string, boolean>>({}); const [busy, setBusy] = useState(false);
  async function load(secret = activeToken) {
    const response = await fetch('/api/admin/contributions', { headers: { Authorization: `Bearer ${secret}` }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setItems(data.contributions); setActiveToken(secret);
  }
  async function action(id: string, status: string) {
    setBusy(true); setError('');
    try { const response = await fetch('/api/admin/contributions', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${activeToken}` }, body: JSON.stringify({ id, status, sourceChecked: checked[id] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); await load(); } catch(e) { setError(e instanceof Error ? e.message : 'Could not moderate.'); } finally { setBusy(false); }
  }
  return <div className="civic-page"><Link href="/works">← Public works</Link><header className="civic-hero"><p className="civic-kicker">Internal · Manual review</p><h1>Contributions</h1></header>{!activeToken ? <form className="civic-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await load(token); setToken(''); setError(''); } catch(e) { setError(e instanceof Error ? e.message : 'Unable to sign in.'); } finally { setBusy(false); } }}><label>Admin token<input type="password" disabled={!ready} value={token} autoComplete="off" onChange={e => setToken(e.target.value)}/></label><button className="civic-action" disabled={!ready || busy}>Open moderation queue</button><p className="civic-muted">Credentials stay in memory for this page. This local pilot requires a server-configured admin token.</p></form> : <><button onClick={() => { setActiveToken(''); setItems([]); }}>Lock queue</button><p>Review each attachment for privacy, relevance and factual wording before publication. Reject allegations or identifying details, or mark needs review. Do not rewrite contributor wording. For documents, check origin and relevance before approval.</p>{!items.length && <p>No contributions yet.</p>}{items.map(c => <article className="civic-section" key={c.id}><p className="civic-kicker">{c.kind} · {c.moderationStatus} · {c.verificationState}</p><h2><Link href={`/works/${c.workId}`}>Work {c.workId} ↗</Link></h2><h3>{c.observationType ?? c.field}</h3><p>{c.note}</p><p>Observed/documented: {c.observationDate} · Submitted: {c.submittedAt}</p><p>{c.approximateLocation}</p><p>Source: citizen · anonymous publicly</p>{c.sourceUrl && <a href={c.sourceUrl} target="_blank" rel="noopener noreferrer">Inspect submitted source ↗</a>}<div className="civic-photos">{c.media.map(m => <figure key={m.id}><PrivateMedia id={m.id} mime={m.mime} token={activeToken}/><figcaption>{m.original_filename} · {m.uploaded_at}</figcaption></figure>)}</div><label className="civic-choice"><input type="checkbox" checked={!!checked[c.id]} onChange={e => setChecked({ ...checked, [c.id]: e.target.checked })}/>I checked relevance, factual wording and privacy{c.kind === 'document' ? ', and verified the source and its supporting claim' : ''}.</label><div className="civic-form-actions"><button className="civic-action" disabled={busy || !checked[c.id]} onClick={() => action(c.id, 'published')}>Publish</button><button disabled={busy} onClick={() => action(c.id, 'rejected')}>Reject</button><button disabled={busy} onClick={() => action(c.id, 'needs_review')}>Needs review</button></div><p className="civic-muted">Receipt {c.id}</p></article>)}</>}{error && <p role="alert" className="civic-error">{error}</p>}</div>;
}
